### ISSUE TITLE
Autoplay or 247

### ISSUE THREAD

**Issue by NICK-FURY-6023** [200percentmicky/chadmusic#14]
Your bot support autoplay music or 247 stay cmd 
You can also add top-gg vote required system 
**Also add Slash / Cmd support**

**Comment by 200percentmicky** [comment]
Auto-play wasn't something I considered at the time when I first made the bot, but I will definitely implement in the future. As for implementing Top-gg's voting system is not planned, and the bot already has slash commands. Are they not showing up when typing in / ?

**Comment by NICK-FURY-6023** [comment]
Or 24/7

**Comment by 200percentmicky** [comment]
24/7 support may be resource intensive depending on where you host the bot, but I will look into implementing that as well in a future release as an optional feature. As for the other features, slash commands have already been implemented a long time ago, and Top-gg voting is not planned. If you're having issues with slash commands not showing up, re-invite your bot with the `bot` and `application.commands` scopes
