### ISSUE TITLE
Listentobot feature

### ISSUE THREAD

**Issue by en0o0n** [200percentmicky/chadmusic#18]
The Mickey-bot is amazing, im really enjoing it alot thankss.

There is a Feature i need, i hope u can make it:

Can you please make like a command for examble "listentobot" to turn off this line:
if (message.author.bot) return;
So when i do "listentobot enable" the music bot can listen to my other bots.

Thanks alot

**Comment by en0o0n** [comment]
I tried to do the selfhosted version of chadmusic and make it listen to other bots
But i sadly could not find the line where (message.author.bot) is.

**Comment by 200percentmicky** [comment]
> I tried to do the selfhosted version of chadmusic and make it listen to other bots But i sadly could not find the line where (message.author.bot) is.

You won't be able to find that check anywhere. It's embedded in discord-akairo, the command framework that the bot uses. 

Anyway, apologies for the long response. I've thought about your request, I feel it's best not to implement it upstream at this time, though I may reconsider it in the future. It's considered a bad practice to have a bot run the commands from another bot, as this could be used to bypass permission checks on users that normally wouldn't have permission to run these commands, but the other bot would. Even if I did implement this feature, I would probably only allow either of the following:
- Either have the feature work for player and filter commands only.
- Only have the feature respond to one bot at a time. (I'd probably do this one, tbh...)

If you do want to have your other bots to respond to your selfhosted copy, you can always run an eval with the following argument: `this.client.commands.blockBots = false`. This will allow the bot to respond to **all bots** in every guild that your bot is a member of. I did test this out for a bit and it seems this may work for your situation, but take note that can caused some unexpected behaviors by allow this to happen.

**Comment by en0o0n** [comment]
Yess you are right.
I think this would be the best soloution -> Only have the feature respond to one bot at a time
