### ISSUE TITLE
Issue with maxtime command

### ISSUE THREAD

**Issue by en0o0n** [200percentmicky/chadmusic#19]
Hello, 

There is a problem with maxtime command -> This problem happens in the selfhosted version and also Mikey-bot:

I sat maxtime to 1 minute 
It usually must ignore the songs over one minute right?
But the FIRST song i play, the bot does not ignore it (The song starts playing), even that he send me the message its ignored.
And right after the bot stucks somehow while using queue command i get then the error: 

![image](https://github.com/200percentmicky/chadmusic/assets/114078231/6faf45fe-998b-419c-881d-2eef6ac1890a)

![image](https://github.com/200percentmicky/chadmusic/assets/114078231/fe049f06-bff8-41c1-9871-5ec52cce3749)

**Comment by 200percentmicky** [comment]
i think i get whats going on. check passes, the song gets removed from the queue, but plays it anyway. queue fails because the metadata doesn't exist. ill look into it when i get a chance today.

**Comment by 200percentmicky** [comment]
needed to rework the logic that removes the track from the queue. honestly something that was needed to be reworked a long time ago. thanks for the report!

**Comment by en0o0n** [comment]
Thanks for reworking on it.
Is it completely fixed now? Can i do $ npm run update ?

**Comment by 200percentmicky** [comment]
its on the develop branch at the moment. ill get it merge to main later.

**Comment by en0o0n** [comment]
And to switch back is `npm run update:main` right ?

**Comment by 200percentmicky** [comment]
no, just `npm run update`
