### ISSUE TITLE
Error when running "npm install"

### ISSUE THREAD

**Issue by S1mp1yDucky** [200percentmicky/chadmusic#21]
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/container/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > distube@5.0.2 prepare
npm ERR! > husky && npm run build
npm ERR! 
npm ERR! .git can't be found
npm ERR! > distube@5.0.2 build
npm ERR! > tsup
npm ERR! 
npm ERR! CLI Building entry: src/index.ts
npm ERR! CLI Using tsconfig: tsconfig.json
npm ERR! CLI tsup v8.3.0
npm ERR! CLI Using tsup config: /home/container/.npm/_cacache/tmp/git-clone60OaTM/tsup.config.ts
npm ERR! CLI Target: es2022
npm ERR! CLI Cleaning output folder
npm ERR! CJS Build start
npm ERR! ESM Build start
npm ERR! CJS dist/index.js     79.10 KB
npm ERR! CJS dist/index.js.map 142.81 KB
npm ERR! CJS ⚡️ Build success in 330ms
npm ERR! ESM dist/index.mjs     75.44 KB
npm ERR! ESM dist/index.mjs.map 142.69 KB
npm ERR! ESM ⚡️ Build success in 331ms
npm ERR! DTS Build start
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN While resolving: typedoc-plugin-extras@3.1.0
npm ERR! npm WARN Found: typedoc@0.25.13
npm ERR! npm WARN node_modules/typedoc
npm ERR! npm WARN   dev typedoc@"^0.25.13" from the root project
npm ERR! npm WARN   1 more (typedoc-material-theme)
npm ERR! npm WARN 
npm ERR! npm WARN Could not resolve dependency:
npm ERR! npm WARN peer typedoc@"0.26.x" from typedoc-plugin-extras@3.1.0
npm ERR! npm WARN node_modules/typedoc-plugin-extras
npm ERR! npm WARN   dev typedoc-plugin-extras@"^3.0.0" from the root project
npm ERR! npm WARN 
npm ERR! npm WARN Conflicting peer dependency: typedoc@0.26.7
npm ERR! npm WARN node_modules/typedoc
npm ERR! npm WARN   peer typedoc@"0.26.x" from typedoc-plugin-extras@3.1.0
npm ERR! npm WARN   node_modules/typedoc-plugin-extras
npm ERR! npm WARN     dev typedoc-plugin-extras@"^3.0.0" from the root project
npm ERR! npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm ERR! npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! src/core/DisTubeVoice.ts(117,7): error TS2322: Type 'InternalDiscordGatewayAdapterCreator' is not assignable to type 'DiscordGatewayAdapterCreator'.
npm ERR!   Types of parameters 'methods' and 'methods' are incompatible.
npm ERR!     Type 'DiscordGatewayAdapterLibraryMethods' is not assignable to type 'InternalDiscordGatewayAdapterLibraryMethods'.
npm ERR!       Types of property 'onVoiceStateUpdate' are incompatible.
npm ERR!         Type '(data: GatewayVoiceState) => void' is not assignable to type '(data: APIVoiceState) => void'.
npm ERR!           Types of parameters 'data' and 'data' are incompatible.
npm ERR!             Type 'APIVoiceState' is not assignable to type 'GatewayVoiceState'.
npm ERR!               Types of property 'member' are incompatible.
npm ERR!                 Type 'import("/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/discord.js/node_modules/discord-api-types/payloads/v10/guild").APIGuildMember | undefined' is not assignable to type 'import("/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/discord-api-types/payloads/v10/guild").APIGuildMember | undefined'.
npm ERR!                   Type 'import("/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/discord.js/node_modules/discord-api-types/payloads/v10/guild").APIGuildMember' is not assignable to type 'import("/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/discord-api-types/payloads/v10/guild").APIGuildMember'.
npm ERR!                     Types of property 'flags' are incompatible.
npm ERR!                       Type 'import("/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/discord.js/node_modules/discord-api-types/payloads/v10/guild").GuildMemberFlags' is not assignable to type 'import("/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/discord-api-types/payloads/v10/guild").GuildMemberFlags'.
npm ERR!                         Property 'IsGuest' is missing in type 'import("/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/discord-api-types/payloads/v10/guild").GuildMemberFlags'.
npm ERR! 
npm ERR! Error: error occured in dts build
npm ERR!     at Worker.<anonymous> (/home/container/.npm/_cacache/tmp/git-clone60OaTM/node_modules/tsup/dist/index.js:1543:26)
npm ERR!     at Worker.emit (node:events:518:28)
npm ERR!     at MessagePort.<anonymous> (node:internal/worker:263:53)
npm ERR!     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
npm ERR!     at exports.emitMessage (node:internal/per_context/messageport:23:28)
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/container/.npm/_cacache/tmp/git-clone60OaTM
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c husky && npm run build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in: /home/container/.npm/_logs/2024-10-01T18_51_23_248Z-debug-0.log

npm ERR! A complete log of this run can be found in: /home/container/.npm/_logs/2024-10-01T18_51_12_741Z-debug-0.log

**Comment by 200percentmicky** [comment]
Looks like the declaration files failed to generate during the build process of my DisTube fork. Should build now in [a31b52c](https://github.com/200percentmicky/chadmusic/commit/a31b52c4fabb3534b093d0d6114dab18392a1240).

**Comment by 200percentmicky** [comment]
If this didn't fix the issue, then delete both package-lock.json and the node_modules folder and run `npm install` again.

**Comment by S1mp1yDucky** [comment]
The NPM build works now and the bot boots up but when running the play command i get this error:

![image](https://github.com/user-attachments/assets/329218f4-06bf-4031-947e-0686575e078d)

![image](https://github.com/user-attachments/assets/52c5c309-09b6-4bfc-9440-f70118548a88)

**Comment by S1mp1yDucky** [comment]
same issue on all 3 vps

**Comment by 200percentmicky** [comment]
I'll see what I can do about that if it's still an ongoing issue for you. But other than that, the bug for this issue has been resolved. Please make a new issue going forward for any other problems.
